[package]
name = "argc"
version = "0.2.0"
edition = "2021"
authors = ["sigoden <sigoden@gmail.com>"]
description = "Parse sehllscript parameters"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/sigoden/argc"
repository = "https://github.com/sigoden/argc"
autotests = false
categories = ["command-line-utilities"]
keywords = ["command-line", "args", "utility"]

[dependencies]
anyhow = "1"
clap = { version = "3", default_features = false, features = ["std"] }
convert_case = "0.5"
nom = "7"

[dev-dependencies]
insta = "1.12"

[profile.release]
lto = true

[[test]]
name = "integration"
path = "tests/tests.rs"